### ISSUE TITLE
Procedural weapon generation

### ISSUE THREAD

**Issue by pagewin** [dmr-capstone/dmr-capstone#182]
This is not a hard requirement of the project, but would significantly improve the enjoyability of the game.

Minimal completion of this is procedural generation of the two existing weapon types in the game via randomized parameters.

Not all of these need to be done by the same person, though things might go more quickly if there is no communication overhead. Even implementing separate weapon mechanics could be done by different people, just expect a few conflicts when merging. Write the changes intelligently to avoid that if that is the case.

- [x] Determine how to adjust weapon stats: based on current difficulty level? What stats are adjusted?
- [ ] Determine weapon "classes" - may require programming additional weapon mechanics which is where the *feature creep* comes in, here are some ideas:
  - **Automatic** (implemented): high fire rate, low damage/cost per shot, low-to-moderate accuracy
  - **Missile** (implemented): high damage, high cost, low fire rate, (not sure about accuracy!)
  - Single-shot (previously implemented; now gone): low damage, low cost, moderate-to-high accuracy, moderate fire rate
  - Shotgun (not implemented): "buckshot" - multiple bullets per trigger pull fired in a cone or fan pattern, individually weak but if all shots connect then it deals high damage, very close range (terrible accuracy at distance due to fan/cone), moderate cost, low fire rate
  - Sniper (not implemented, very similar to missile but with different parameterization): high damage, high cost, high-to-perfect accuracy, very low fire rate, possibly implement headshot/weak spot mechanic to OHKO (one-hit knockout) enemies based on body part hit
  - Explosive (not implemented, but would work similar to exploding objects already in game): high damage, very high cost, area of effect, possibly damages player if caught in blast, possibly destroys objects caught in blast, extremely low fire rate
  - Proximity and/or remote mines or other traps (not implemented): moderate damage, moderate cost, area of effect, damages player if caught in blast, requires luring enemies to trapped location (potential for creating smarter AI that detects and avoids these in higher difficulties), low fire rate
- [x] Determine how weapon classification influences randomization of parameters
- [x] Determine how weapon parameters/class affects weapon cost in shop
- [x] Implement procedural generation (very simple parameterized generation); requires acceptable formulae that will vary based on above point regarding weapon classification
- [x] Randomize shopkeeper's inventory using procedurally generated weapons

**Comment by pagewin** [comment]
Extra weapon types are very low priority, will work on this with only the 2 implemented types in mind

If someone wants to implement more weapon mechanics, go ahead
