### ISSUE TITLE
Create the enemy AI

### ISSUE THREAD

**Issue by yhbautista** [dmr-capstone/dmr-capstone#21]
- [x] Add basic enemy movement - #22 
- [x] Add enemy movement towards the player - #23
- [x] Add enemy attacks - #24
- [x] Research artificial intelligence for enemy NPCs - #25
- [ ] Add advanced enemy movement - #26
- ~~Add advanced enemy attacks - #27~~
