### ISSUE TITLE
Program Win Condition

### ISSUE THREAD

**Issue by mturpen98** [dmr-capstone/dmr-capstone#42]
- [x] Decide on all "win" conditions #38 

- [x] Write code to trigger a win #39 

- [x] Make end game transition screen #40

- [x] Link back to main menu #41

- [x] Allow player to continue playing after victory
