### ISSUE TITLE
Plan and Execute Usability Studies

### ISSUE THREAD

**Issue by yhbautista** [dmr-capstone/dmr-capstone#63]
- [x] Create First Usability Study Plan - #64 
- [x] Recruit First Study Participants - #65
- [x] Execute First Study - #66
- [x] Create Second Usability Study Plan - ~~#67~~ #165 
- [x] Recruit Second Study Participants - #68
- [x] Execute Second Study - #69
